### ISSUE TITLE
ErrorException: Undefined variable $response in Middleware.php

### ISSUE THREAD

**Issue by kent013** [hotmeteor/spectator#136]
Hi, I'm using 1.7.1.

When I have some error with my openapi spec, like 

```
ErrorException: Path [GET /api/v1/organizations/{organization}/projects/{project}] not found in spec.
```

then

```
ErrorException: Undefined variable
```

will occur at https://github.com/hotmeteor/spectator/blob/develop/src/Middleware.php#L68-L80

because `$response` is defined inside of try-catch block.
I don't know how to correctly fix this.
Currently just adding null safe.

```
        return $response ?? null;
```

full trace is

```
ErrorException: Undefined variable $response in /var/www/html/vendor/hotmeteor/spectator/src/Middleware.php:80
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/vendor/hotmeteor/spectator/src/Middleware.php(80): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Spectator\Middleware->handle()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router->dispatchToRoute()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\Routing\Router->dispatch()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(545): Illuminate\Foundation\Http\Kernel->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(511): Illuminate\Foundation\Testing\TestCase->call()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(324): Illuminate\Foundation\Testing\TestCase->json()
#30 /var/www/html/tests/Feature/Http/Api/V1/ProjectsTest.php(210): Illuminate\Foundation\Testing\TestCase->getJson()
#31 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(1548): Tests\Feature\Http\Api\V1\ProjectsTest->testGet200()
#32 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(1154): PHPUnit\Framework\TestCase->runTest()
#33 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#34 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(904): PHPUnit\Framework\TestResult->run()
#35 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(673): PHPUnit\Framework\TestCase->run()
#36 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(673): PHPUnit\Framework\TestSuite->run()
#37 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(673): PHPUnit\Framework\TestSuite->run()
#38 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(661): PHPUnit\Framework\TestSuite->run()
#39 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner->run()
#40 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run()
#41 /var/www/html/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#42 /var/www/html/vendor/bin/phpunit(123): include('...')
#43 {main}
```

**Comment by ricardonolan** [comment]
If your OpenAPI spec is incorrect, then the test is correct to fail, it's really up to you, how you want to handle the $response.
Spectator only checks if the $response matches the OpenAPI spec.

**Comment by kent013** [comment]
@ricardonolan 
I think it is not problem on my code.

The problem is variable `$response` is declared in the try-catch scope. If there is a exception one of `InvalidPathException|MalformedSpecException|MissingSpecException|TypeErrorException|UnresolvableReferenceException`, then `$response` is not declared, and it will cause a `undefined variable` error at Line 80. 

Since the code captures exception instead of rethrow the exception, I think it is better to fix the error.

**Comment by ricardonolan** [comment]
> @ricardonolan I think it is not problem on my code.
> 
> The problem is variable `$response` is declared in the try-catch scope. If there is a exception one of `InvalidPathException|MalformedSpecException|MissingSpecException|TypeErrorException|UnresolvableReferenceException`, then `$response` is not declared, and it will cause a `undefined variable` error at Line 80.
> 
> Since the code captures exception instead of rethrow the exception, I think it is better to fix the error.

Can you show the code?

**Comment by kent013** [comment]
@ricardonolan 
 https://github.com/hotmeteor/spectator/blob/develop/src/Middleware.php#L68-L80

```php
        try {
            $response = $this->validate($request, $next);
        } catch (InvalidPathException|MalformedSpecException|MissingSpecException|TypeErrorException|UnresolvableReferenceException $exception) {
            $this->spectator->captureRequestValidation($exception);
        } catch (\Throwable $exception) {
            if ($this->exceptionHandler->shouldReport($exception)) {
                return $this->formatResponse($exception, 500);
            }

            throw $exception;
        }

        return $response;
```

I don't know it is okay to return null from this method (working in my project though).

**Comment by ricardonolan** [comment]
I meant to show the code of your test, which is causing the error.

**Comment by ricardonolan** [comment]
My point is this, taking the below example from docs.

```
<?php

use Spectator\Spectator;

class ExampleTest extends TestCase
{
    /**
     * A basic functional test example.
     *
     * @return void
     */
    public function testBasicExample()
    {
        Spectator::using('Api.v1.json');

        $response = $this->postJson('/user', ['name' => 'Sally']);

        $response
            ->assertValidRequest()
            ->assertValidResponse(201);
    }
}
```

If you don't have a spec for the /user endpoint, then it is correct to give the error:
`ErrorException: Path [GET /user] not found in spec.`

I'm not sure why you'd want it to return null here, since that would mean the testCase could pass, when it shouldn't.
If you don't want a specific test to run through spectator, simply don't include it in the test function.

**Comment by kent013** [comment]
@ricardonolan 
Hmm...?

$response is not defined because Exception reported.
Not because the spec definition is corrupted.

I think Spectator should report Exception one of

```
(InvalidPathException|MalformedSpecException|MissingSpecException|TypeErrorException|UnresolvableReferenceException $exception)
```

not PHP error ErrorException.

```
[message] => Undefined variable $response
    [exception] => ErrorException
    [file] => /vendor/hotmeteor/spectator/src/Middleware.php
```

**Comment by kent013** [comment]
@ricardonolan 
for clarification, 

When I have a API like

```
GET /api/v1/organizations/{organization}/projects/{project}]
```

and if I mistyped plural projects as `project` like

```
GET /api/v1/organizations/{organization}/project/{project}]
```

And run test code like below,

```
    /**
     * get /api/v1/organization/{organization_id}/projects/{project_id} Get status code 200
     */
    public function testGet200(): void
    {
        /** @var User $user */
        $user = User::factory()->create();
        $organization = Organization::factory()->createWithDefaultTeamAndRole($user, OrganizationRole::Owner());
        $project = Project::factory()->createWithDefaultTeamAndRole($user, $organization, ProjectRole::Owner());

        $parameters = [
            'organization' => $organization->id,
            'project' => $project->id,
        ];

        $response = $this->actingAs($user)
            ->getJson(create_url('/api/v1/organizations/{organization}/projects/{project}', $parameters))
            ->assertStatus(200)
            ->assertValidRequest()
            ->assertValidResponse();

        $this->assertNotEmpty($response['data']);
        $this->assertEquals($project->id, $response['data']['id']);
    }
```

reports 

```
sail@9ce8fcc97615:/var/www/html$ composer exec phpunit -- --filter=ProjectsTest::testGet200
PHPUnit 9.5.26 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 00:05.577, Memory: 54.50 MB

There was 1 failure:

1) Tests\Feature\Http\Api\V1\ProjectsTest::testGet200
Expected response status code [200] but received 500.
Failed asserting that 200 is identical to 500.

The following exception occurred during the last request:

ErrorException: Undefined variable $response in /var/www/html/vendor/hotmeteor/spectator/src/Middleware.php:82
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/vendor/hotmeteor/spectator/src/Middleware.php(82): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Spectator\Middleware->handle()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router->dispatchToRoute()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\Routing\Router->dispatch()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(545): Illuminate\Foundation\Http\Kernel->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(511): Illuminate\Foundation\Testing\TestCase->call()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(324): Illuminate\Foundation\Testing\TestCase->json()
#30 /var/www/html/tests/Feature/Http/Api/V1/ProjectsTest.php(234): Illuminate\Foundation\Testing\TestCase->getJson()
#31 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(1548): Tests\Feature\Http\Api\V1\ProjectsTest->testGet200()
#32 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(1154): PHPUnit\Framework\TestCase->runTest()
#33 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#34 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(904): PHPUnit\Framework\TestResult->run()
#35 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(673): PHPUnit\Framework\TestCase->run()
#36 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(673): PHPUnit\Framework\TestSuite->run()
#37 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(673): PHPUnit\Framework\TestSuite->run()
#38 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(661): PHPUnit\Framework\TestSuite->run()
#39 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner->run()
#40 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run()
#41 /var/www/html/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#42 /var/www/html/vendor/bin/phpunit(123): include('...')
#43 {main}

----------------------------------------------------------------------------------

Undefined variable $response

/var/www/html/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:231
/var/www/html/tests/Feature/Http/Api/V1/ProjectsTest.php:235

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
Script phpunit handling the __exec_command event returned with error code 1
```

When I add a null safe at Middleware.php, 

```
 return $response ?? null;
```

will get Exception which I needed.

```
sail@9ce8fcc97615:/var/www/html$ composer exec phpunit -- --filter=ProjectsTest::testGet200
PHPUnit 9.5.26 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 00:06.811, Memory: 54.50 MB

There was 1 error:

1) Tests\Feature\Http\Api\V1\ProjectsTest::testGet200
ErrorException: Path [GET /api/v1/organizations/{organization}/projects/{project}] not found in spec.
Failed asserting that true is false.

/var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:124
/var/www/html/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:99
/var/www/html/vendor/hotmeteor/spectator/src/Assertions.php:39
/var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:124
/var/www/html/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:99
/var/www/html/tests/Feature/Http/Api/V1/ProjectsTest.php:236
```

**Comment by ricardonolan** [comment]
Are you sure you have an up to date Spectator?
When I run a test with a missing spec, I do get the following (without having to add `return $response??null;`:
```
ErrorException: Path [GET /api/rest/jobsall] not found in spec.
Failed asserting that true is false.
```

**Comment by kent013** [comment]
@ricardonolan 
I'm using v1.7.1 (latest tag)

**Comment by kent013** [comment]
The code I mentioned is added via this PR.
https://github.com/hotmeteor/spectator/issues/118

**Comment by hotmeteor** [comment]
Ya, that's interesting. It's clearly hitting one of the possible request exceptions but as a 500 error. I wonder if one of them shouldn't be included.

**Comment by ronaldwanink** [comment]
Same issue here.
